[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "electricity_forecasting"
version = "0.0.1"
description = "A short description of the project."
authors = [
  { name = "Simone Cherry-Delisle" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "ipython",
    "jupyterlab",
    "loguru",
    "matplotlib",
    "mkdocs",
    "noaa-sdk",
    "notebook",
    "numpy",
    "openml",
    "pandas",
    "pip",
    "plotly",
    "pytest",
    "python-dotenv",
    "ruff",
    "scikit-learn",
    "tables",
    "tqdm",
    "typer",
]
requires-python = "~=3.12.0"


[tool.ruff]
line-length = 99
src = ["electricity_forecasting"]
include = ["pyproject.toml", "electricity_forecasting/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["electricity_forecasting"]
force-sort-within-sections = true

